name: "Build project with Nix and Push to GHCR"

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20

      - uses: cachix/cachix-action@v12
        with:
          name: elxreno-rust
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build container image stream
        run: |
          nix build .#dockerImage -L
          echo "image_stream=$(readlink result)" >> $GITHUB_ENV
          echo "image_tag=$(nix eval .#dockerImage --apply 'p: p.imageTag')" >> $GITHUB_ENV

      - name: Push image to GHCR
        if: github.ref == 'refs/heads/main'
        run: |
          ${{ env.image_stream }} | pigz | \
            skopeo copy --dest-creds "${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}" \
            docker-archive:/dev/stdin \
            docker://ghcr.io/price-tracker/backend:${{ env.image_tag }}
